---
stages:
- name: build dhir-nginx
  inputs:
  - service: ${SAMPLE_REPO}
    type: git
    branch: master
    dir_name: null
  triggers:
  - type: none
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy dhir-nginx
  inputs:
  - type: job
    stage: build dhir-nginx
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -n dhir-nginx-devops -d mybluemix.net -f bluemix/dev-manifest.yml
