---
stages:
- name: build dhir-nginx
  inputs:
  - url: https://github.com/MOHLTC11/icon-r2-dhir-nginx.git
    type: git
    branch: master
    dir_name: null
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy dhir-nginx
  inputs:
  - type: job
    stage: build dhir-nginx
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ibm:yp:us-south
      organization: PHDPexperimental
      space: ICONDevOps
      application: dhir-nginx-devops
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -n dhir-nginx-devops -d mybluemix.net -f bluemix/dev-manifest.yml
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
