---
stages:
- name: Build frontend
  inputs:
  - service: ${SAMPLE_REPO}
    type: git
    branch: master
    dir_name: null
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy frontend
  inputs:
  - type: job
    stage: Build frontend
    job: Build
    dir_name: null
  properties:
  - name: ICON_DOMAIN
    type: text
    value: ${ICON_DOMAIN}
  - name: BLUE_GREEN
    type: text_area
    value: ${DEPLOY_SCRIPT}
  - name: ICON_SERVER_NAME
    type: text
    value: ${ICON_SERVER_NAME}
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash    
      echo "${BLUE_GREEN}" > blue_green.sh
      chmod +x blue_green.sh
      ./blue_green.sh  -d ${ICON_DOMAIN} -n hph -f bluemix/base-manifest.yml --no-start
      
      cf set-env ${CF_APP} ICON_SERVER https://${ICON_SERVER_NAME}.${ICON_DOMAIN}
      cf start ${CF_APP}
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
