---
stages:
- name: build-icon-kibana
  inputs:
  - service: ${SAMPLE_REPO}
    type: git
    branch: master
    dir_name: null
  jobs:
  - name: Build
    type: builder
- name: deploy icon kibana
  inputs:
  - type: job
    stage: build-icon-kibana
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: "#!/bin/bash\ncf push \"${CF_APP}\" -f bluemix/dev-manifest.yml -n icon-kibana-devops\
      \ -d mybluemix.net \n"
